# Generated by Django 3.0.3 on 2021-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shoping_cart', to='products.Product', verbose_name='Carrinho de compras'),
        ),
    ]
