# Generated by Django 3.0.3 on 2021-04-07 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificação')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saldo em conta')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Bonus em conta')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer', verbose_name='Apostador')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'conta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificação')),
                ('movimentacao', models.CharField(choices=[], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('movi_data', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'historico',
                'verbose_name_plural': 'historicos',
                'db_table': 'historicoconta',
                'managed': True,
            },
        ),
    ]
