# Generated by Django 3.0.3 on 2021-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='movimentacao',
            field=models.CharField(choices=[('sc', 'Comprar creditos'), ('wc', 'Retirar creditos'), ('b', 'Bonus')], max_length=20),
        ),
    ]
