# Generated by Django 3.0.3 on 2021-04-21 23:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='events',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Minuto a minuto'),
        ),
        migrations.AlterField(
            model_name='match',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Informações adicionais'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Resultado detalhado'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport_id',
            field=models.PositiveIntegerField(choices=[('1\t ', 'Soccer'), ('18', 'Basketball'), ('13', 'Tennis'), ('91', 'Volleyball'), ('78', 'Handball'), ('16', 'Baseball'), ('17', 'Ice Hockey'), ('14', 'Snooker'), ('12', 'American Football'), ('3\t ', 'Cricket'), ('83', 'Futsal'), ('15', 'Darts'), ('92', 'Table Tennis'), ('94', 'Badminton'), ('8\t ', 'Rugby Union'), ('19 ', 'Rugby League'), ('36', 'Australian Rules'), ('66', 'Bowls'), ('9\t ', 'Boxing/UFC\t'), ('75', 'Gaelic Sports'), ('90', 'Floorball\t'), ('95', 'Beach Volleyball'), ('110', 'Water Polo\t'), ('107', 'Squash'), ('151', 'E-sports')], default='1\t ', verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Detalhes da partida'),
        ),
    ]
