# Generated by Django 3.0.3 on 2021-04-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210421_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sport_id',
            field=models.CharField(choices=[('1\t ', 'Soccer'), ('18', 'Basketball'), ('13', 'Tennis'), ('91', 'Volleyball'), ('78', 'Handball'), ('16', 'Baseball'), ('17', 'Ice Hockey'), ('14', 'Snooker'), ('12', 'American Football'), ('3\t ', 'Cricket'), ('83', 'Futsal'), ('15', 'Darts'), ('92', 'Table Tennis'), ('94', 'Badminton'), ('8\t ', 'Rugby Union'), ('19 ', 'Rugby League'), ('36', 'Australian Rules'), ('66', 'Bowls'), ('9\t ', 'Boxing/UFC\t'), ('75', 'Gaelic Sports'), ('90', 'Floorball\t'), ('95', 'Beach Volleyball'), ('110', 'Water Polo\t'), ('107', 'Squash'), ('151', 'E-sports')], default='1\t ', max_length=50, verbose_name='Sport'),
        ),
    ]
