version: '3.3'

services:
  # Postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=kdkfjajr54111
      - POSTGRES_DB=db_app
  

  django:
    build: .
    command: ["./run.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db