# Generated by Django 3.0.3 on 2021-04-07 21:44

import core.base.fields
import core.base.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Changer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120, verbose_name='Rua')),
                ('street_number', models.CharField(default='sn', max_length=50, verbose_name='Número da casa')),
                ('district', models.CharField(max_length=80, verbose_name='Bairro')),
                ('city', models.CharField(max_length=80, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia '), ('CE', 'Ceará'), ('DF', 'Distrito Federal '), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('complement', models.CharField(blank=True, max_length=250, verbose_name='Complemento')),
                ('zip_code', core.base.fields.ZipCodeField(max_length=9, validators=[core.base.validators.validate_zip_code], verbose_name='Cep')),
                ('phone_prefix', models.CharField(max_length=2, verbose_name='DDD')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Telefone')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
                ('sex', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=15, verbose_name='Sexo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('bench', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='benches.Bench', verbose_name='Banca')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cambista',
                'verbose_name_plural': 'Cambistas',
            },
        ),
    ]
