# Generated by Django 3.0.3 on 2021-04-07 21:44

import core.base.fields
import core.base.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120, verbose_name='Rua')),
                ('street_number', models.CharField(default='sn', max_length=50, verbose_name='Número da casa')),
                ('district', models.CharField(max_length=80, verbose_name='Bairro')),
                ('city', models.CharField(max_length=80, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia '), ('CE', 'Ceará'), ('DF', 'Distrito Federal '), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('complement', models.CharField(blank=True, max_length=250, verbose_name='Complemento')),
                ('zip_code', core.base.fields.ZipCodeField(max_length=9, validators=[core.base.validators.validate_zip_code], verbose_name='Cep')),
                ('phone_prefix', models.CharField(max_length=2, verbose_name='DDD')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Telefone')),
                ('type_person', models.CharField(choices=[('CPF', 'Pessoa Física'), ('CNPJ', 'Pessoa Jurídica')], default='CPF', max_length=5, verbose_name='Tipo de pessoa')),
                ('document', core.base.fields.CnpjField(max_length=18, validators=[core.base.validators.validate_cnpj], verbose_name='Documento')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nome da banca')),
                ('responsible', models.CharField(max_length=250, verbose_name='Nome do responsável')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Banca',
                'verbose_name_plural': 'Bancas',
                'managed': True,
            },
        ),
    ]
