# Generated by Django 3.0.3 on 2021-02-15 15:23

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.stock.products.utils
import ecommerce.stock.products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço de atacado')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço de revenda')),
                ('product_code', models.CharField(max_length=150, verbose_name='Código do produto')),
                ('quantity_products', models.PositiveIntegerField(default=1, verbose_name='Quantidade de produtos')),
                ('unit_measurement_type', models.CharField(choices=[('ampère', 'Ampère intensidade de corrente elétrica'), ('coulomb', 'carga elétrica, quantidade de eletricidade)'), ('cal', 'Caloria'), ('cd', 'Candela (intensidade luminosa)'), ('cg', 'Centigrama'), ('cL', 'Centilitro'), ('cm', 'Centímetro'), ('cm²', 'Centímetro quadrado'), ('cm³', 'Centímetro cúbico'), ('eV', 'eV elétron-volt (energia)'), ('g', 'Grama'), ('GW', 'Gigawatt'), ('gray', 'Gray (dose absorvida)'), ('ha', 'Hectare (área)'), ('hg', 'Hectograma'), ('Hz', 'Hertz (frequência)'), ('K', 'Kelvin (temperatura termodinâmica)'), ('kcal', 'Quilocaloria'), ('kg', 'Quilograma'), ('kHz', 'Quilo-hertz'), ('kL', 'Quilolitro'), ('km', 'Quilômetro'), ('km²', 'Quilômetro quadrado'), ('kW', 'Quilowatt'), ('kWh', 'Quilowatt-hora'), ('L', 'Litro (volume)'), ('lb', 'Libra'), ('lm', 'Lúmen (fluxo luminoso)'), ('m', 'Metro'), ('m²', 'Metro quadrado'), ('m³', 'Metro cúbico'), ('mg', 'Miligrama'), ('MHz', 'Mega-hertz'), ('min', 'Minuto'), ('mL', 'Mililitro'), ('mm', 'Milímetro'), ('mm²', 'Milímetro quadrado'), ('mm³', 'Milímetro cúbico'), ('mol', 'Mol (quantidade de matéria)'), ('oz', 'Onça (massa)'), ('Pa', 'Pascal (pressão)'), ('pH', 'Potencial hidrogeniônico'), ('ppm', 'Parte por milhão'), ('rpm', 'Rotação por minuto'), ('rps', 'Rotação por segundo'), ('s', 'Segundo (tempo)'), ('sc', 'Saca (1 saca = "60 kg")'), ('t', 'Tonelada (massa) (= "1 Mg)"'), ('V', 'Volt (diferença de potencial)'), ('VA', 'Volt-ampère'), ('var', 'Var (potência reativa)')], default='g', max_length=50, verbose_name='Tipo de unidade de medida')),
                ('unit_measurement_value', models.FloatField(verbose_name='Valor da unidade de medida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand', verbose_name='Marca')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to=ecommerce.stock.products.utils.product_image_path, validators=[ecommerce.stock.products.validators.validade_dimensions_image_product], verbose_name='Foto')),
                ('is_main_image', models.BooleanField(default=False, verbose_name='Imagem principal?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Produto')),
            ],
        ),
    ]
