# Generated by Django 3.0.3 on 2021-04-07 21:44

import accounts.customers.customers.models
import core.base.fields
import core.base.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('prolile', models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.customers.customers.models.customer_path, verbose_name='Foto de perfil')),
                ('birth_date', models.DateField()),
                ('cpf', core.base.fields.CpfField(max_length=14, unique=True, validators=[core.base.validators.validate_cpf], verbose_name='CPF')),
                ('pix_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
