from django.db.models import TextChoices

class SportIDChoices(TextChoices):
  Soccer = '1	 ', 'Soccer'
  Basketball = '18',	'Basketball'
  Tennis = '13',	'Tennis'
  Volleyball = '91',	'Volleyball'
  Handball = '78',	'Handball'
  Baseball = '16',	'Baseball'
  IceHockey = '17',	'Ice Hockey'
  Snooker = '14',	'Snooker'
  AmericanFootball = '12',	'American Football'
  Cricket = '3	 ', 'Cricket'
  Futsal = '83',	'Futsal'
  Darts = '15',	'Darts'
  TableTennis = '92',	'Table Tennis'
  Badminton = '94',	'Badminton'
  RugbyUnion = '8	 ', 'Rugby Union'
  RugbyLeague = '19 ', 'Rugby League'
  AustralianRules = '36',	'Australian Rules'
  Bowls = '66',	'Bowls'
  BoxingUFC	 = '9	 ', 'Boxing/UFC	'
  GaelicSports = '75',	'Gaelic Sports'
  Floorball	 = '90',	'Floorball	'
  BeachVolleyball = '95',	'Beach Volleyball'
  WaterPolo	 = '110',	'Water Polo	'
  Squash = '107',	'Squash'
  ESports = '151', 'E-sports'