# Generated by Django 3.0.3 on 2021-02-15 15:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código da venda')),
                ('gateway', models.CharField(choices=[('cielo', 'Cielo'), ('mercadopago', 'Mercado Pago'), ('paypal', 'PayPal'), ('iugu', 'Iugu'), ('pagarme', 'Pagar.me')], max_length=50, verbose_name='Gateway')),
                ('invoice_id', models.CharField(max_length=250)),
                ('installments', models.PositiveSmallIntegerField(default=1)),
                ('pay_type', models.CharField(choices=[('credit_card', 'Cartão de crédito'), ('bank_slip', 'Boleto'), ('pix', 'Pix')], max_length=50, verbose_name='Tipo de pagamento')),
                ('pay_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('canceled', 'Cancelado'), ('refused', 'Recusado'), ('expired', 'Expirado'), ('refunded', 'Reembolsado'), ('chargeback', 'Chargeback'), ('in_protest', 'Contestada')], default='pending', max_length=50, verbose_name='Situação do pagamento')),
                ('is_verificated', models.BooleanField(default=False, verbose_name='Verificado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product', verbose_name='Produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Sale', verbose_name='Pedido')),
            ],
        ),
    ]
