from django.db.models import  TextChoices
from django.utils.translation import gettext_lazy as _

class UnitOfMeasurementChoice(TextChoices):
  A = 'ampère', _('Ampère intensidade de corrente elétrica')
  C = 'coulomb', _('carga elétrica, quantidade de eletricidade)')
  CAL = 'cal', _('Caloria')
  CD = 'cd', _('Candela (intensidade luminosa)')
  CG = 'cg', _('Centigrama')
  CL = 'cL', _('Centilitro')
  CM = 'cm', _('Centímetro')
  CM2 = 'cm²', _('Centímetro quadrado')
  CM3 = 'cm³', _('Centímetro cúbico')
  EV = 'eV', _('eV elétron-volt (energia)')
  G = 'g', _('Grama')
  GW = 'GW', _('Gigawatt')
  Gy = 'gray', _('Gray (dose absorvida)')
  HA = 'ha', _('Hectare (área)')
  HG = 'hg', _('Hectograma')
  HZ = 'Hz', _('Hertz (frequência)')
  K = 'K', _('Kelvin (temperatura termodinâmica)')
  KCAL = 'kcal', _('Quilocaloria')
  KG = 'kg', _('Quilograma')
  KHZ = 'kHz', _('Quilo-hertz')
  KL = 'kL', _('Quilolitro')
  KM= 'km', _('Quilômetro')
  KM2 = 'km²', _('Quilômetro quadrado')
  KW = 'kW', _('Quilowatt')
  KWH = 'kWh', _('Quilowatt-hora')
  L = 'L', _('Litro (volume)')
  LB = 'lb', _('Libra')
  LM = 'lm', _('Lúmen (fluxo luminoso)')
  M = 'm', _('Metro')
  M2 = 'm²', _('Metro quadrado')
  M3 = 'm³', _('Metro cúbico')
  MG = 'mg', _('Miligrama')
  MHZ = 'MHz', _('Mega-hertz')
  MIN = 'min', _('Minuto')
  ML = 'mL', _('Mililitro')
  MM = 'mm', _('Milímetro')
  MM2 = 'mm²', _('Milímetro quadrado')
  MM3 = 'mm³', _('Milímetro cúbico')
  MOL = 'mol', _('Mol (quantidade de matéria)')
  OZ = 'oz', _('Onça (massa)')
  PA = 'Pa', _('Pascal (pressão)')
  PH = 'pH', _('Potencial hidrogeniônico')
  PPM = 'ppm', _('Parte por milhão')
  RPM = 'rpm', _('Rotação por minuto')
  RPS = 'rps', _('Rotação por segundo')
  S = 's', _('Segundo (tempo)')
  SC = 'sc', _('Saca (1 saca = "60 kg")')
  T = 't', _('Tonelada (massa) (= "1 Mg)"')
  V = 'V', _('Volt (diferença de potencial)')
  VA = 'VA', _('Volt-ampère')
  VAR = 'var', _('Var (potência reativa)')

